### ISSUE TITLE
no screen shot created

### ISSUE THREAD

**Issue by stevez** [anishkny/playwright-test-coverage#41]
I run your tests, and try to make test failed, then the video and trace are created, but no screen shot image.

**Comment by stevez** [comment]
It is mentioned here: https://github.com/microsoft/playwright/issues/7777

**Comment by anishkny** [comment]
Hi @stevez I am not sure if this issue is related to **code coverage**. This repo provides a plugin on top of Playwright for measuring code coverage. Not related to screenshots.

**Comment by stevez** [comment]
I feel you misunderstood what I mean, if you run your tests example, try to make the test failed, you will notice that trace map and video are captured, but no screen shot, since you configured  screenshot: "only-on-failure", 
https://github.com/anishkny/playwright-test-coverage/blob/b8571a3fcce11ba6f4c335187ed1991af564d81a/test/playwright.config.js#L12

The thing is if people use your plugin get the coverage, but they can't capture the screen shot, what can they do?  There is no way they can fix by themselves.

**Comment by anishkny** [comment]
Sorry for the confusion and thanks for clarification. I think I can reproduce this but not sure if it is an issue with this plugin. Looking.

**Comment by anishkny** [comment]
Yup as shown [here](https://github.com/mxschmitt/playwright-test-coverage/pull/9/files) this line needs to be removed:

https://github.com/anishkny/playwright-test-coverage/blob/4d0e0cbffd7466b19d12ccab1fd6b4e1e0cf0bcf/index.js#L35
