### ISSUE TITLE
standard-version is deprecated

### ISSUE THREAD

**Issue by anishkny** [anishkny/playwright-test-coverage#60]
Consider using [absolute-version/commit-and-tag-version](https://github.com/absolute-version/commit-and-tag-version)

**Comment by kachkaev** [comment]
Take a look at https://github.com/changesets/changesets too – neat tool!

**Comment by anishkny** [comment]
Thanks for the suggestion. But [changesets](https://github.com/changesets/changesets) seems geared towards monorepo and perhaps overkill for a simple library like this one. Also, [absolute-version/commit-and-tag-version](https://github.com/absolute-version/commit-and-tag-version) claims to be a drop-in replacement which helps.
