### ISSUE TITLE
[Question] When do you plan to release the ISTANBUL_TEMP_DIR Option?

### ISSUE THREAD

**Issue by mstysk** [anishkny/playwright-test-coverage#69]
1.1.0 doesn't seem to include the ISTANBUL_TEMP_DIR Option.

I would like this feature very much.

**Comment by kachkaev** [comment]
Good point @mstysk! 1.1.0 was released on 2022-07-21 but https://github.com/anishkny/playwright-test-coverage/pull/61 got merged a day after that. In the meantime, you can [create a patch](https://github.com/blockprotocol/blockprotocol/blob/fb1af9f270ecbb9c6a8faaa29ea59a5d26427d98/patches/playwright-test-coverage%2B1.1.0.patch#L1) via [`patch-package`](https://www.npmjs.com/package/patch-package), which will give you a workaround until 1.2.0 is released.

**Comment by anishkny** [comment]
Released [v1.2.0](https://github.com/anishkny/playwright-test-coverage/commit/7ffb779039e7fcb41da2c78b4ffd709c4b9f41d3).

**Comment by mstysk** [comment]
thank you!
