### ISSUE TITLE
Measures test files instead of application

### ISSUE THREAD

**Issue by charles-testco** [anishkny/playwright-test-coverage#87]
I have just configured this and when I run it prints out coverage for my test files instead of application code.
My tests are in a subfolder called e2e.

`-----------------------|---------|----------|---------|---------|-------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------|---------|----------|---------|---------|-------------------
All files              |   30.69 |     6.12 |    0.94 |   31.57 |                   
 pages                 |    3.44 |        0 |       0 |    3.44 |                   
  basePage.ts          |    3.44 |        0 |       0 |    3.44 | 9-243             
 setup                 |     100 |       50 |     100 |     100 |                   
  local.config.ts      |     100 |       50 |     100 |     100 | 24           `

Additionally, it does not seem to recognize  *.spec.ts as test file

**Comment by anishkny** [comment]
Hmm, thats weird.

Would it be possible to create a simple repo demonstrating the issue you are seeing?
