### ISSUE TITLE
[Question] Running tests from VSCode throws error

### ISSUE THREAD

**Issue by jarnovanrhijn** [anishkny/playwright-test-coverage#93]
First off :), thanks for the plugin!

So I have this weird issue where running tests through the playwright extension in VSCode results in an error.
The error thrown is:
`browserContext.addInitScript: Error: Object with guid @... was not bound in the connection`

It doesn't happen when running it via `npm / yarn` or when using `@playwright/test`.

However, I seem to have found a way to work around the issue by setting trace to `trace: 'retain-on-failure',` or `on` but this decreases performance.

I hope this makes sense in the absence of an extensive example, if it doesn't I will try to elaborate a bit more.

**Comment by anishkny** [comment]
Hmm, I was unable to reproduce on the test in this repo [`test/tests/app.spec.js`](https://github.com/anishkny/playwright-test-coverage/blob/main/test/tests/app.spec.js).

I am using VSCode 1.74.2 (Universal) and [Playwright Test for VSCode v1.0.3](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright).

I ran the test using the Run Test button in Test Explorer:

<img width="1648" alt="Screen Shot 2023-01-05 at 11 58 15 AM" src="https://user-images.githubusercontent.com/357499/210869255-2d162a58-95dd-48d2-aa4f-48143f615807.png">

It still generated the coverage for me.

**Comment by jarnovanrhijn** [comment]
Could you try setting the config of playwright as followed and duplicate the test? Maybe it's just my config that is not complete.

```
const config = {
  reporter: "line",
  forbidOnly: !!process.env.CI,
  workers: 1,
  use: {
    headless: !!process.env.CI,
    ignoreHTTPSErrors: true,
    trace: "on-first-retry",
  },
};
```
<img width="759" alt="Screenshot 2023-01-06 at 11 09 07" src="https://user-images.githubusercontent.com/2767127/210979088-e414c87c-17fa-40ac-9d2e-917a5fb78adf.png">

<img width="2087" alt="Screenshot 2023-01-06 at 11 06 33" src="https://user-images.githubusercontent.com/2767127/210978633-27c9f1ea-48ed-40b0-b243-7f1db4a41dd5.png">
